#!/usr/bin/env node
/**
 * Writes src/version.ts from package.json "version", so the SDK identifies itself
 * (X-ProofAge-Sdk, User-Agent) with the version it was published as.
 *
 * Runs on its own as the npm "version" lifecycle script: `npm version <patch|minor>`
 * bumps package.json, then this regenerates the constant and stages it. The
 * SDK_VERSION test in tests/sdk-identification.test.ts fails if the two drift.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

writeFileSync(
  new URL('../src/version.ts', import.meta.url),
  `// Generated by scripts/sync-version.mjs from package.json. Do not edit by hand.\n` +
    `export const SDK_VERSION = '${version}';\n`,
);

console.log(`src/version.ts -> ${version}`);
